FROM ubuntu:20.04
FROM ruby:2.3.1

ENV RAILS_ROOT /app

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs imagemagick

RUN mkdir -p $RAILS_ROOT
WORKDIR $RAILS_ROOT
ADD Gemfile* $RAILS_ROOT/
RUN bundle install
COPY . ./
EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
